# frozen_string_literal: true

# Golden conformance: fixtures generated by edge-analyst/scripts/gen-fixtures.mjs, with expected
# outputs computed by running the reference implementation (src/blocklist.js) itself. A failure
# here means the port drifted from the format owner — fix the port, never the fixture. This is
# the Ruby twin of camada-core/test/conformance.test.ts and camada-python's test_conformance.py,
# case for case.
RSpec.describe "conformance" do
  cases = Fixtures.read_json("blk3/cases.json")
  cases5 = Fixtures.read_json("blk5/cases.json")["v5"]
  hdrs_fx = Fixtures.read_json("blk3/hdrs.json")

  def matcher(name, d = "blk3")
    Camada::Snapshot::Matcher.new(Camada::Snapshot.parse_snapshot(Fixtures.read_bin("#{d}/#{name}.bin"), Fixtures.read_json("#{d}/#{name}.meta.json")))
  end

  # A v5 case's `headers` is a map with already lower-cased keys — the request as the tap sees
  # it. It becomes the header(name) getter §D3 defines, exactly as the reference harness does.
  def as_input(c)
    i = c["input"].transform_keys(&:to_sym)
    headers = i.delete(:headers)
    Camada::Snapshot::MatchInput.new(**i, header: headers ? ->(n) { headers[n] } : nil)
  end

  # the reference reports "nothing matched" as reason null; the port leaves it nil too
  def outcome(r) = { "block" => r.block, "challenge" => r.challenge, "allowed" => r.allowed, "reason" => r.reason }
  def outcome5(r) = outcome(r).merge("warn" => r.warn, "action" => r.action, "rule" => r.rule)
  def label(c) = JSON.generate(c["input"])

  %w[v3 v4].each do |version|
    describe version do
      it "matches the basic cases" do
        m = matcher("#{version}-basic")
        cases[version]["basic"].each { |c| expect(outcome(m.match(as_input(c)))).to eq(c["expect"]), label(c) }
      end

      it "matches the empty cases" do
        m = matcher("#{version}-empty")
        cases[version]["empty"].each { |c| expect(outcome(m.match(as_input(c)))).to eq(c["expect"]), label(c) }
      end
    end
  end

  describe "v4 outcomes" do
    it "never sets two outcome flags" do
      m = matcher("v4-basic")
      (cases["v4"]["basic"] + cases["v4"]["empty"]).each do |c|
        r = m.match(as_input(c))
        expect([r.allowed, r.block, r.challenge].count(true)).to be <= 1
      end
    end

    it "cannot express allow or challenge from a v3 container" do
      v3 = matcher("v3-basic")
      pairs = cases["v4"]["basic"].zip(cases["v3"]["basic"])
      diverged = pairs.reject { |a, b| a["expect"] == b["expect"] }
      expect(diverged).not_to be_empty # the fixtures must actually exercise the new sections
      diverged.each { |v4c, v3c| expect(outcome(v3.match(as_input(v4c)))).to eq(v3c["expect"]) }
    end
  end

  describe "v5" do
    it "matches the rules cases" do
      m = matcher("v5-rules", "blk5")
      cases5["rules"].each { |c| expect(outcome5(m.match(as_input(c)))).to eq(c["expect"]), label(c) }
    end

    it "matches the empty cases" do
      m = matcher("v5-empty", "blk5")
      cases5["empty"].each { |c| expect(outcome5(m.match(as_input(c)))).to eq(c["expect"]), label(c) }
    end

    it "never sets two outcome flags" do
      m = matcher("v5-rules", "blk5")
      (cases5["rules"] + cases5["empty"]).each do |c|
        r = m.match(as_input(c))
        expect([r.allowed, r.block, r.challenge, r.warn].count(true)).to be <= 1
      end
    end

    it "names the rule only when a rule decided" do
      m = matcher("v5-rules", "blk5")
      cases5["rules"].each do |c|
        r = m.match(as_input(c))
        if r.reason == "rule"
          expect(r.rule).to be_truthy
          expect(r.action).to be_truthy
        else
          expect([r.rule, r.action]).to eq([nil, nil])
        end
      end
    end

    it "lets rules overrule the sides a v4 container can only read" do
      v4 = matcher("v4-basic")
      rules = matcher("v5-rules", "blk5")
      diverged = cases5["rules"].reject { |c| outcome(v4.match(as_input(c))) == outcome(rules.match(as_input(c))) }
      expect(diverged).not_to be_empty
      diverged.each { |c| expect(c["expect"]["reason"]).to eq("rule") }
    end

    it "decides header cases through the getter alone" do
      m = matcher("v5-rules", "blk5")
      header_cases = cases5["rules"].select { |c| c["input"]["headers"] }
      expect(header_cases).not_to be_empty
      header_cases.each do |c|
        expect(outcome5(m.match(as_input(c)))).to eq(c["expect"])
        blind = m.match(Camada::Snapshot::MatchInput.new(**c["input"].except("headers").transform_keys(&:to_sym))) # no getter: a header condition can never fire
        if c["expect"]["reason"] == "rule"
          expect(blind.rule).not_to eq(c["expect"]["rule"])
        else
          expect(blind.reason).to eq(c["expect"]["reason"])
        end
      end
    end
  end

  it "keeps interleaved matchers' state apart" do
    a = matcher("v4-basic")
    b = matcher("v4-empty")
    20.times do
      expect(a.match(Camada::Snapshot::MatchInput.new(ip: "2001:db8::1")).reason).to eq("ip6")
      expect(b.match(Camada::Snapshot::MatchInput.new(ip: "2001:db8::1")).block).to be(false)
      expect(a.match(Camada::Snapshot::MatchInput.new(ip: "2001:db8::2")).block).to be(false)
    end
  end

  describe "HDRS bitmask" do
    it "pins the exact header order" do
      expect(Camada::Events::HDRS).to eq(hdrs_fx["hdrs"])
    end

    it "reproduces the hm vectors" do
      hdrs_fx["cases"].each do |c|
        info = Camada::Events::RequestInfo.new(method: "GET", host: "x.test", path: "/", query: "", headers: c["names"].map { |n| [n, "v"] }, ip: "1.2.3.4")
        expect(Camada::Events.build_wire_event(info, tap: "sdk-node", rid: "r")["hm"]).to eq(c["hm"]), c["names"].join("+")
      end
    end
  end
end
