#!/usr/bin/env ruby
# frozen_string_literal: true

# Re-vendors @camada/browser's auto build into lib/camada/beacon_js.rb.
#
# Usage: ruby scripts/sync_beacon.rb [path/to/camada-browser]   (defaults to the sibling checkout)
# Run `npm run build` in camada-browser first; spec/beacon_js_spec.rb fails until the two agree.
require "digest"
require "json"

root = File.expand_path("..", __dir__)
browser = ARGV[0] || File.expand_path("../camada-browser", root)
src = File.read(File.join(browser, "dist", "auto.global.js"), encoding: "UTF-8")
version = JSON.parse(File.read(File.join(browser, "package.json")))["version"]
out = File.join(root, "lib", "camada", "beacon_js.rb")
File.write(out, <<~RUBY)
  # frozen_string_literal: true

  # GENERATED by scripts/sync_beacon.rb — do not edit. The first-party beacon (@camada/browser's
  # dist/auto.global.js) vendored as a String literal: served at /_cam/b.js with no runtime file
  # read. spec/beacon_js_spec.rb pins it to the sibling build byte for byte.
  module Camada
    BEACON_VERSION = #{version.inspect}
    BEACON_SHA256 = #{Digest::SHA256.hexdigest(src).inspect}
    BEACON_JS = #{src.inspect}
  end
RUBY
puts "beacon_js.rb: @camada/browser/#{version}, #{src.bytesize} bytes"
